#!/usr/bin/env bash
# A bash script that transferes a file from our client to a server

FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

if [ "$#" -lt "4" ]; then
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY';
else
    ssh-add "$PATH_TO_SSH_KEY";
    scp -o StrictHostKeyChecking=no "$FILE" "$USERNAME@$IP":~;
fi
