#!/usr/bin/env bash
# A bash script that transfers a file from our client to a server

FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

if [ "$#" -lt "4" ]; then
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY';
else
    scp -i "$PATH_TO_SSH_KEY" StrictHostKeyChecking=no \
	"$FILE" "$USERNAME@$IP":~/;
fi
