#!/usr/bin/env bash
# A bash sctipt that configures a new Ubuntu machine to respect
# certain requrements

sudo apt-get update
sudo apt install -y nginx-full
sudo ufw allow 'Nginx HTTP'
cd /var/www/html/
sudo chmod a+w index.html
sudo echo 'Hello World' > index.html
sudo service nginx restart
