#!/usr/bin/env bash
# A bash sctipt that configures a new Ubuntu machine to respect
# certain requrements

apt-get update
apt install -y nginx-full
ufw allow 'Nginx HTTP'
cd /var/www/html/
chmod a+w index.html
echo 'Hello World' > index.html
service nginx restart
