#!/usr/bin/env bash
# A bash sctipt that configures a new Ubuntu machine to respect
# certain requrements

sudo apt install nginx-full && cd /var/www/html/ && \
sudo mv index.html index.html.bak && sudo touch index.html && \
sudo chmod a+w index.html && sudo echo 'Hello World!\n' > index.html && \
sudo service nginx restart
