#!/usr/bin/env bash
# This script manages 'manage_my_process'

if [ $# -gt 0 ]
then
    if [ "$1" == "start" ]
    then
	sudo ./manage_my_process &
	sudo touch /var/run/my_process.pid
#	echo $(pgrep -f manage_my_process) > /var/run/my_process.pid
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
    elif [ "$1" == "stop" ]
    then
#	kill $(pgrep -f manage_my_process)
	kill "$(cat /var/run/my_process.pid)"
	echo "manage_my_process stopped"
	rm -f /var/run/my_process.pid
    elif [ "$1" == "restart" ]
    then
#	kill $(pgrep -f manage_my_process)
	kill "$(cat /var/run/my_process.pid)"
	sudo rm -f /var/run/my_process.pid
	sudo ./manage_my_process &
	sudo touch /var/run/my_process.pid
#	echo $(pgrep -f manage_my_process) > /var/run/my_process.pid
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process restarted"
    else
	echo "Usage: manage_my_process {start|stop|restart}"
    fi
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
