#!/usr/bin/env bash
# A bash script that configures a web server so that
# it redirects port 8080/TCP to port 80/TCP

# Setup and Install
sudo apt-get update -y
sudo apt-get install -y ufw

# Necessary Configurations
sudo ufw allow in proto tcp from any port 22  && \
sudo ufw allow in proto tcp from any port 443 && \
sudo ufw allow in proto tcp from any port 80  && \
sudo ufw route allow in on any from any out on any proto tcp port 8080 to any port 80 && \
sudo ufw deny in from any                     && \
sudo ufw reload                               && \
sudo sed -i 's/#net\/ipv4\/ip_forward=1/net\/ipv4\/ip_forward=1/' /etc/ufw/sysctl.conf && \
sudo sed -i 's/#net\/ipv6\/conf\/default\/forwarding=1/net\/ipv6\/conf\/default\/forwarding=1/' /etc/ufw/sysctl.conf && \
sudo sed -i 's/#net\/ipv6\/conf\/all\/forwarding=1/net\/ipv6\/conf\/all\/forwarding=1/' /etc/ufw/sysctl.conf && \

echo "

---> DONE ---
"
#net/ipv4/ip_forward=1
#net/ipv6/conf/default/forwarding=1
#net/ipv6/conf/all/forwarding=1
